- mtools/mgenerate/mgenerate_spec.md
It's fixed in wiki as well
https://github.com/rueckstiess/mtools/wiki/mgenerate/_compare/9dd4441582d031f0f32b08c64b203d9d4d679ca7...9faa2479c3231dc6304373db720574af57aed0fc
> Fix $missing operator option

- mtools/mlogvis/mlogvis.py
Sometimes it could be useful to make it possible to set the max count of lines till mlogvis plots querie lines to html output. For me sometimes 10000 is  a little bit less. So it could be helpful to set it via command line.
> make max line count for mlogvis plot configurable via command line

- mtools/util/logevent.py
fix #357 (LogFile: handle newlines lines)
> Fix mloginfo not ignoring log lines that don't start with a date

- mtools/mlaunch/mlaunch.py
Accounts for changes made in the latest release of Pymongo.
- Don't use MongoClient.alive() in wait_for_host; this method doesn't exist anymore, causing an Exception to be thrown which in turn causes wait_for_host to loop when toStart=True.
- Explicitly specify new serverSelectionTimeoutMS argument when pinging mongod/s, to prevent Pymongo 3.0 from waiting default 30 seconds if the server isn't actually up.
> - fixes issue #351 : excessive wait on mlaunch init/start/etc with Pymongo 3.0

- mtools/mlaunch/mlaunch.py
See #387 for details.
The basic idea is that we have to be careful about catching NoSuchProcess errors when using psutils on El Capitan.
Please have a look and lead me know if I need to make any changes to get this submitted!
> Fix for psutils zombie process exceptions on El Capitan

- mtools/mlaunch/mlaunch.py
was originally #392, but cherry-picked change because of merge conflicts.
> Fix mlaunch list TypeError occuring on --startup (#354)

- CHANGES.md
- mtools/mlaunch/mlaunch.py
- requirements.txt
Fixed #439, #438 
Added verbose debug statements from a comment on #437 
Updated change log as per updates from git log
"csrs" is used by default when version > 3.3.0
Again, by default, only one config server is created (a replica set of one if "csrs")
The on-line documentation still needs to be updated to describe the the "csrs" parameter
> Fixes csrs

- mtools/mlaunch/mlaunch.py
1. Force an error on missing token
2. Reverse search for leading 'v'
3. Print out detected version on --verbose
> Fix 451: Improve version detection

- CHANGES.md
- mtools/mlaunch/mlaunch.py
Truncates the trailing release candidate part of string. 
If `mongod` version  is "db version v3.4.0-rc2", then the version parsed is "3.4.0". Hopefully, the release candidate 'versions' are always prefixed is a hyphen '-'.
> completed fix for 451

- mtools/test/test_mlogfilter.py
- mtools/test/test_util_logfile.py
Log file parsing tests have hardcoded years in them and the logfiles
do not contain any year information, so when the year changes, the
tests start failing. This change calculates the correct year values
based on the current date.
This commit fixes the unit test failures on the other pull requests in
2017.
> Calculate current year so the tests will also work next year

- mtools/test/test_util_logevent.py
- mtools/util/logevent.py
LogEvent timestamp were wrongly calculated, resulting in this log line:
```
2017-08-25T22:23:49.097+0000 I COMMAND [conn0]
```
to be rendered like this:
```
2017-08-25T22:23:49.970+0000 I COMMAND [conn0]
```
Note that `097` changed to `970` in the processed line.
This was not noticed for a long while, and the tests passed because the tests were using a timestamp of:
```
2013-08-03T21:52:05.995+1000
```
which due to the bug, was processed correctly.
I have fixed the timestamp processing and updated the test.
> Fixed incorrect timestamp processing in LogEvent

- mtools/mlaunch/mlaunch.py
Log "no such file or directory" instead of "ValueError: substring not
found".
> Better error if --binarypath is wrong

- mtools/test/test_mlogfilter.py
- mtools/util/logfile.py
* Added a sanity check to exit if no valid log lines are found at the beginning of a file:
> Error: < filename > does not appear to be a supported MongoDB log file format
* Skip repeated calculation of details for a log file; the lazy evaluation of properties could trigger multiple futile calculations for missing properties
> Fix #429: mloginfo and other tools should check if the log file passed in is a valid log

- mtools/mlaunch/mlaunch.py
Since options may be passed through to either `mongod` or `mongos`, it is possible that one of those may accept a given parameter.
With this PR there will be a warning for the first time an argument is ignored for a given binary, eg:
mlaunch init --replica 2 --shards 1  --carrots --apples 2 --binaryPath foo
warning: ignoring unknown argument --carrots for mongod
warning: ignoring unknown argument --apples for mongod 
warning: ignoring unknown argument --binaryPath for mongod
warning: ignoring unknown argument --carrots for mongos
warning: ignoring unknown argument --apples for mongos
warning: ignoring unknown argument --binaryPath for mongos
> Fix #355: mlaunch should print warning message for invalid options

- mtools/mplotqueries/plottypes/base_type.py
Specifically: avoid black, move colors with connotations (red, green) to be used less often, and add two greys.
Fixes #453.
> Adjust plot colors

- mtools/mlaunch/mlaunch.py
Replica sets can have up to 7 voting members[1].
This change allows spinning up replica sets with more than 7 members by forcing
zero votes starting from the 8th node.
[1] https://docs.mongodb.com/manual/reference/limits/#replica-sets
> mlanunch: Make 8th+ replica set members non-voting

- mtools/mlaunch/mlaunch.py
- mtools/test/test_mlaunch.py
* index value for config_docs is now taken from args
* Add simple test for --name parameter
Index value for config_docs is now taken from args istead of fixed value.
Tested by manually creating named replicaset with --auth directly from commandline.
Unit test written aswell.
O/S testing:
| Linux            |
> Fix #476: Error while creating replica set with name and auth args

- .travis.yml
- requirements.txt
- setup.py
- test-requirements.txt
- tox.ini
- remove current test lines from setup.py
- add tox.ini
- add test-requirements.txt
- add coverage report
- add flake8 with pep8-naming, isort, and pep257 as testenvs
- update .travis.yml
> Fix #543: Enable tox

- mtools/mlaunch/mlaunch.py
- mtools/test/test_mlaunch_commandlines.py
Rebased PR #555, added test for the PR.
> Fix for #554: Using --hostname with mlaunch in 3.6 causes deploying failure

- mtools/mlaunch/mlaunch.py
- mtools/test/test_mlaunch_commandlines.py
> Fix for #556: mlaunch: Require shard servers to be replica sets (3.6.1+)

- mtools/test/test_mloginfo.py
Starting in 2018, the tests started failing because they depend on the current year. I've updated the test to pass. Feel free to take this approach or another.
> Update year to match the current year.

- mtools/mlaunch/mlaunch.py
Work around [SERVER-31916](https://jira.mongodb.org/browse/SERVER-31916).
Before this change starting a 3.6 replica set or sharded cluster with auth fails with the following error:
```
$ python -m mtools.mlaunch.mlaunch init --replicaset --node 2 --auth --verbose --hostname localhost
Detected mongod version: 3.6.3
creating directory: /Users/shane/tmp-mtools/data/replset/rs1/db
Detected mongod version: 3.6.3
creating directory: /Users/shane/tmp-mtools/data/replset/rs2/db
Detected mongod version: 3.6.3
writing .mlaunch_startup file.
waiting for nodes to shutdown...
launching: mongod --replSet replset --dbpath /Users/shane/tmp-mtools/data/replset/rs1/db --logpath /Users/shane/tmp-mtools/data/replset/rs1/mongod.log --port 27017 --fork --keyFile /Users/shane/tmp-mtools/data/keyfile …
```
> Allow starting 3.6 clusters with PyMongo 3.6.1

- mtools/mlaunch/mlaunch.py
So long as drivers haven't implemented SCRAM-SHA-256, create accounts
with old auth mechanism so authentication still works.
> Create user with SCRAM-SHA-1 mechanism

- mtools/mlaunch/mlaunch.py
This (fake) version is commonly used when compiling development versions of the
MongoDB server (via `scons MONGO_VERSION=0.0.0`) (as a way of avoiding
unnecessarily rebuilding version-related object files after each commit).
However, a mongod version of `0.0.0` caused `mlaunch --csrs` to exit, since
(apparently) `"0.0.0" < "3.1.0"`.  This prevented `mlaunch --sharded` from
launching sharded clusters of current development versions of MongoDB which
have been compiled this way.
This change makes mlaunch use `--csrs` when the mongod version is `0.0.0`,
which allows it to work correctly with all currently supported server branches
(v3.2, v3.4, v3.6, master) that have been compiled with `MONGO_VERSION=0.0.0`.
O/S testing:
| Linux …
> Force `mlaunch --csrs` when "version" is `0.0.0`

- mtools/mlaunch/mlaunch.py
- mtools/test/test_mlaunch_commandlines.py
> Handle spaces in mlaunch `binarypath` parameter in Unix and Windows.

- mtools/mlaunch/mlaunch.py
- mtools/test/test_mlaunch.py
The `_convert_u2b()` method no longer appears to be required with the recent updates for Py2/3 support. This causes KeyErrors in Python 3.6.5 and removal appears to keep both py27 and py36 happy.
> Fix #596: mlaunch: KeyError: 'port' with Python 3.6.5

- mtools/mplotqueries/mplotqueries.py
Before:
<pre>
% ~/.local/bin/mplotqueries ./mongod.log
Traceback (most recent call last):
File "/home/w/.local/bin/mplotqueries", line 7, in <module>
from mtools.mplotqueries.mplotqueries import main
File "/home/w/.local/lib/python2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 22, in <module>
raise ImportError("Can't import matplotlib. See "
ImportError: Can't import matplotlib. See github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.
</pre>
OK, let's see what the deal is with matplotlib:
<pre>
averagest% python
Python 2.7.15 (default, May  1 2018, 05:55:50)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or …
> Report actual error when import fails in mplotqueries.

- mtools/mlaunch/mlaunch.py
This is one of a number of patches Cloud has been using in a forked version of mtools.
We would like to merge these & start using master instead.
- fixed errors reported by pyflakes
- if mongod binary is missing, print the path that was used.
> Pyflakes and error on missing mongod

- mtools/mlaunch/mlaunch.py
This is one of a number of patches Cloud has been using in a forked version of mtools. 
We would like to merge these & start using master instead. 
This PR: 
- enable passing --nopreallocj to mongod
- raise if user addition fails.
> Enable passing --nopreallocj to mongod

- mtools/mlaunch/mlaunch.py
This is one of a number of patches Cloud has been using in a forked version of mtools.
We would like to merge these & start using master instead.
> Add users to all shards in sharded cluster

- mtools/util/logfile.py
When processing some logs from our mongo 3.4.15 server we ran into this decoding issue:
```python
Traceback (most recent call last):
File "testenv/bin/mloginfo", line 11, in <module>
sys.exit(main())
File "/Users/matthewthompson/testenv/lib/python2.7/site-packages/mtools/mloginfo/mloginfo.py", line 95, in main
tool.run()
File "/Users/matthewthompson/testenv/lib/python2.7/site-packages/mtools/mloginfo/mloginfo.py", line 58, in run
if self.logfile.hostname else "unknown"))
File "/Users/matthewthompson/testenv/lib/python2.7/site-packages/mtools/util/logfile.py", line 154, in hostname
self._iterate_lines()
File "/Users/matthewthompson/testenv/lib/python2.7/site-packages/mtools/util/logfile.py", line 275, in _iterate_lines
line = line.decode("utf-8-sig")
File …
```
> Replace characters that can't be decoded with '?'

- mtools/test/test_util_logevent.py
- mtools/util/logevent.py
There was a logic error in logevent.py regarding parsing an empty log line, or an unexpected log line. 
This PR fixed the logic issue (introduced in https://github.com/rueckstiess/mtools/commit/2836eb07b208e97fe3a97e73f253383eda2481d3), which was not caught at the time because the test does not check for this specific case.
> Fixed issue #618

- mtools/test/test_util_logevent.py
- mtools/util/logevent.py
Log lines `Scheduled new oplog query` could contain a text similar to:
```
... maxAttempts: 1 maxTimeMillis: -1ms
```
at the end of the line. The LogEvent parser erroneously decided that since it ends with a `<number>ms`, it must be a query with a `<number>ms` duration. However, this is not a query, and the trailing `-1ms` should not be interpreted as a duration value.
> Added an exception for 'Scheduled new oplog query' from duration parsing. Fixes #619

- mtools/mplotqueries/mplotqueries.py
- mtools/mplotqueries/plottypes/scatter_type.py
In `mplotqueries` legend, if any text contains two dollar signs, it will be interpreted by matplotlib as a mathtext. This resulted in unexpected formatting.
Currently this is the default behaviour of matplotlib and cannot be disabled: https://github.com/matplotlib/matplotlib/issues/4938
The current solution is to escape the dollar signs in the legend labels to disable unexpected mathtext formatting. This should fix #613
> Escape dollar signs in mplotqueries legend. Fixes #613

- mtools/test/test_mlogfilter.py
mlogfilter test would intermittently fail due to lack of microsecond value passed into the test.
This has been a longstanding issue in mtools tests.
> Fix intermittent mlogfilter test failure

- mtools/util/cmdlinetool.py
Due to Python 2.7's magic, redirecting output to a file or anything other than a terminal will not honour the host's locale setting. This means that output redirection will default to ASCII, which will crash e.g. `mlogfilter` when unicode characters are present in the log file. This was the cause of #643.
Since MongoDB log files are `utf-8` by default, we think it's a better solution to enforce this encoding on `sys.stdout` instead of relying on the user remembering to set `PYTHONIOENCODING`.
To make things more interesting, nose monkey patches `sys.stdout` (https://github.com/nose-devs/nose/issues/1065). This necessitates detecting if nose is being used, otherwise tests will fail.
Python 3 does not appear to have this issue. Redirects are so far safer compared to 2.7.
> Ensure sys.stdout is unicode

- mtools/mlaunch/mlaunch.py
- mtools/mlogfilter/mlogfilter.py
- mtools/mloginfo/sections/connection_section.py
- mtools/mloginfo/sections/rs_info_section.py
- mtools/mplotqueries/mplotqueries.py
- mtools/mplotqueries/plottypes/range_type.py
- mtools/mplotqueries/plottypes/scatter_type.py
- mtools/test/test_mlaunch.py
- mtools/test/test_mlaunch_commandlines.py
- mtools/test/test_mloginfo.py
- mtools/test/test_util_presplit.py
- mtools/util/cmdlinetool.py
- tox.ini
Tidy up per `tox -e flake8`
Ensure all tests passing on flake8, py27, and py36 envs
O/S testing:
| Linux            | 
| macOS            |  10.13.5
| Windows          |
> Fix: #652: Resolve flake8 complaints

- mtools/mlaunch/mlaunch.py
Set PyMongo client appname to `mlaunch v#.##`
Verified that application.name appears in 3.4+ logs, eg:
2018-09-03T15:55:04.917+1000 I NETWORK  [conn1] received client metadata from 127.0.0.1:56334 conn1: { driver: { name: "PyMongo", version: "3.6.0" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.6" }, platform: "CPython 2.7.14.final.0", application: { name: "mlaunch v1.5.2-dev" } }
> Fix #662: mlaunch should specify appname

- mtools/mlaunch/mlaunch.py
Resolves #661 by using the `roles` variable once it's been constructed in order to handle the case where roles are supplied on the command line as documents as opposed to just the role name string. This is important when `--auth-db` is going to be something other than admin, like `$external`.
Sample command which did not work before because role doc was being passed directly as a role name:
```
mlaunch init --sharded do re me --config 3 --mongos 2 --replicaset --nodes 3 --oplogSize 100 --dir /data/db/shtest/ --port 28017 --binarypath /usr/local/mongodb/bin/ --noprealloc --nopreallocj --smallfiles --hostname gmbp.local \
--auth --username admin --password mongodb --auth-db admin \
--auth-role-docs \
--auth-roles "{ \"role\": \"dbAdminAnyDatabase\", \"db\": \"admin\" }" "{ \"role\": …
```
> Only use roles variable instead of args once it's set up

- mtools/mlaunch/mlaunch.py
Allow options like "--networkMessageCompressors=disabled". Before this
change, mlaunch would warn "ignoring unknown argument". Now, arguments
that include "=" are properly matched with the arguments supported by
the selected mongod.
> Permit command line options with "="

- mtools/mlaunch/mlaunch.py
- Don't warn about `--wiredTigerCacheSizeGB` being an unknown argument for `mongos`
- Fix comparison of `binary` value (required when `binarypath` is prepended to `binary`)
> Fix #670: --wiredTigerCacheSizeGB warning for sharded cluster

- .travis.yml
- INSTALL.md
- README.rst
- doc/index.rst
- doc/install.rst
- doc/release.rst
- doc/testing.rst
- setup.py
- tox.ini
This PR removes the badges & testing for Python 2.7 (aka "no longer supported"), but doesn't attempt to remove any technical debt for Python 2-3 compatibility.
> Fix #694: Remove support for Python 2.7

- .travis.yml
- README.rst
- doc/install.rst
- mtools/mlogfilter/mlogfilter.py
- mtools/mplotqueries/plottypes/base_type.py
- mtools/util/grouping.py
- mtools/util/logfile.py
- requirements.txt
- setup.py
- tox.ini
> Fix #682: Add support for Python 3.7

- mtools/mlogvis/mlogvis.py
Fix this problem:
```
$ mlogvis --line-max 1000000 mongod.log
Traceback (most recent call last):
File "/home/user/.local/bin/mlogvis", line 10, in <module>
sys.exit(main())
File "/home/user/.local/lib/python3.6/site-packages/mtools/mlogvis/mlogvis.py", line 114, in main
tool.run()
File "/home/user/.local/lib/python3.6/site-packages/mtools/mlogvis/mlogvis.py", line 87, in run
json_docs = self._export(True)
File "/home/user/.local/lib/python3.6/site-packages/mtools/mlogvis/mlogvis.py", line 50, in _export
if with_line_str and out_count > self.args['line_max']:
TypeError: '>' not supported between instances of 'int' and 'str'
```
> Add correct type to `--line-max` argument

- mtools/mloginfo/sections/query_section.py
Some of our queries don't have durations in the logs because compose.com truncated the log lines at 1100 characters. This change means that `mloginfo` still shows count statistics for these lines even though no durations were present. The other statistics that are related to the durations are still represented as `-`s. Better than nothing for us!
Remove the duration from the query log lines and run `mloginfo` across it. Now you'll get the count and no other stats.
We have tested on macOS.
> Include queries without durations in the query count

- doc/mlaunch.rst
- mtools/mlaunch/mlaunch.py
- Reconciled undocumented parameters in `mlaunch init --help`
- Replaced SSL with TLS/SSL in option help text to match upstream server documentation
- Removed unimplemented `--auth-role-docs` option
- Rename `--no-initial-user` to `--initial-user` to match actual usage
> Fix #666: SSL parameters to mlaunch are not documented on website

- .gitignore
- mtools/util/logevent.py
- mtools/util/pattern.py
in `mtools/utils/pattern.py` a behavior change from py2 to py3 (string.encode('utf-u')) generates a byte string output and not a standart unicode string. And thus, JSON can't serialize this output later.
As mtools 1.6.0 no longer is Python 2.7 compatible, and in Python3 all strings are unicode the part that generates the problem isn't needed anymore. Also used the opportunity to remove 'six' package (introduced on Python 2 to Python3 transition).
Also added `ensure_ascii=False` to json.dumps call so that unicode chars are printed as 'chars' and not as octa or hex char codes.
```       
return json.dumps(doc, sort_keys=True, separators=(', ', ': '), ensure_ascii=False)
```
i've added an additional test case in `mtools/utils/pattern.py`  for this situation
```
##
##
s = (r'{_id: …
```
> Fix/bugre #764 json serialize crash w bytes instead of str in pattern.py

- mtools/mlaunch/mlaunch.py
In a sharded replica set, wait for each of the shards to elect
a primary before continuing to hopefully fix #691
> Wait for each RS to elect a primary

- mtools/data/index.html
Update link to d3js to "protocol-less" link, so browser can decide wheather to use http or https.
The problem was, when publishing result on domain with https support.
Changed link to d3js from http://d3js... to //d3js...
O/S testing:
| Linux            | 
| macOS            | 
| Windows          |
> Update link to d3js

- mtools/util/logevent.py
Changed embedded double-quotes to single quotes so JSON parsing doesn't choke
> Fix #803: mloginfo --clients misses driver connections with embedded quotes in platform metadata

- mtools/mlaunch/mlaunch.py
- mtools/mplotqueries/mplotqueries.py
- mtools/util/logfile.py
- mtools/util/presplit.py
- add __getstate__ to avoid serialising LogFile TextIOWrapper object
- set pickle protocol version to 4 for compatibility (instead of -1/highest)
- remove unnecessary __future__ imports
> Fix #818: mplotqueries --overlay example not working

- doc/mlaunch.rst
instead of `--auth-user` and `--auth-password` it should just be `--username` and `--password`
> fix typo in docs about username and password flags

- mtools/mlaunch/mlaunch.py
- `--auth` only adds `--keyFile` if not already provided on the command line
- quote the `--keyFile` param added by `--auth` so paths with embedded spaces don't break
- warn if user-provided `--keyFile` can't be read
- make sure `--auth` for `mlaunch` processing also sets `--auth` for `mongod` and `mongos`
> Fix #830: mlaunch: --auth does not quote --keyFile parameter

- mtools/mlaunch/mlaunch.py
When mlaunch fails to spawn mongod or mongos, it tries to output a log excerpt. This exceprt can be useless in some situations, e.g.:
```
launching: config server on port 16046                                                                                 
b'{"t":{"$date":"2022-06-23T00:01:17.482Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParam
eter options","attr":{"serverParameters":{"enableTestCommands":{"default":false,"value":true}}}}\nabout to fork child p
rocess, waiting until server is ready for connections.\nforked process: 6585\nERROR: child process failed, exited with 
48\nTo see additional information in this output, start without the "--fork" option.\n'                                
can't start process, return code 48. tried to launch: …
```
> Output the log path when mongod/mongos launch fails

- mtools/mlaunch/mlaunch.py
+ python3 -m mtools.mlaunch.mlaunch --dir /tmpfs/db --binarypath /opt/mongodb/bin --setParameter enableTestCommands=1 --setParameter acceptApiVersion2=1 --setParameter diagnosticDataCollectionEnabled=false --replicaset --name test-rs --nodes 2 --arbiter
Fatal error trying get output from `/opt/mongodb/bin/mongod`.Is the binary in your path?
O/S testing:
| Linux            | 
| macOS            | 
| Windows          |
> Report exception message when binary invocation fails

- mtools/mlaunch/mlaunch.py
This fixes a few bugs with TLS options in mlaunch.
* None of the `--tls*` args were actually passed on the CLI to `mongod` or `mongos`.
* The `pymongo` client does not accept a `tls_cert_reqs` option.
* The `tlsAllowInvalidCertificates` must be `True` or `False`.
* If `--tlsAllowInvalidHostnames` is passed on the CLI, the `tlsAllowInvalidHostnames` option should be `True`, not `False`
* When constructing options for the `pymongo` client, the TLS options are `tlsCertificate*`, not `tlsClientCertificate*`. In addition, the only option for passing the cert is called `tlsCertificateKeyFile`. There's no `tlsCertificate` option. As such, this PR removed the corresponding `--tlsClientCertificate` option.
I ran this command after running `python setup.py`:
```
python …
```
> Fix tls issues

- requirements.txt
- setup.py
* The `psutil` package name was missing in the `setup.py`, causing running `setup.py` to fail.
* The `packaging` module is used by `mlaunch` but was not added to its prereqs.
> Fix missing package name in extras requirements and add missing prereq
