rueckstiess/mtools

mtools/mplotqueries/mplotqueries.py
=> mplotqueries: enable grid by default

mtools/mplotqueries/plottypes/scatter_type.py
Fixes #243, which is a bug that severely impacts nscanned/n plots
(it makes them Just Plain Wrong, and so basically useless).
=> mplotqueries nscanned/n: Scale correctly

mtools/mlaunch/mlaunch.py
=> Config Server as Replica sets (CSRS) support, fixes #399.

mtools/mlaunch/mlaunch.py
=> Allow --setParameter options.

README.md
Thought I'd seen cleaner ones somewhere, like https://github.com/tomchristie/django-rest-framework
=> Switch README status images from PNGs to SVGs

mtools/mlaunch/mlaunch.py
I also removed "votes" because I didn't see an advantage to setting each member's votes.
=> New --priority option forces first member primary

mtools/mlaunch/mlaunch.py
Important for a casual user: "Great, I started a cluster! How do I log in?"
=> mlaunch init: print username and password

mtools/mlaunch/mlaunch.py
Add support on running mlaunch in windows.
=> Support mlaunch on windows

mtools/util/logfile.py
- add sanity check to prevent infinite loops when recursing through previous lines
=> Improve #301: mlogfilter loops forever for some datetimes

mtools/mlogfilter/filters/logline_filter.py
- also order filterArgs more consistently
=> Fix #504: mlogfilter --component and --planSummary values should be case-insensitive

mtools/util/parse_sourcecode.py
Updated `parse_sourcecode.py` and generated new `log2code.pickle` for MongoDB r2.4.0 through r3.4.9. Included MongoDB 2.4 and 2.6 for completeness as there are still a few holdouts despite these release series being End-of-Life.
Tested against 3.0, 3.2, and 3.4 log files with `mloginfo --distinct` and `mloginfo --distinct --verbose` using the old and new log2code pickle files.
=> Fix #537: Update log2code data for MongoDB 3.0+

requirements.txt
=> Remove argparse from requirements.txt

mtools/mlaunch/mlaunch.py
=> Join paths correctly for OS

doc/conf.py
=> Remove 'view source' links from docs

doc/index.rst, doc/mgenerate.rst
=> Remove mgenerate from documentation

README.rst
=> Update README with gh-pages links for documentation

mtools/mlaunch/mlaunch.py
This is one of a number of patches Cloud has been using in a forked version of mtools.
We would like to merge these & start using master instead.
=> Add support for GSSAPI

mtools/mplotqueries/mplotqueries.py, mtools/mplotqueries/plottypes/scatter_type.py, requirements.txt, setup.py
Now using matplotlib 2.2.2 and numpy 1.14.5. Fixes #623.
=> Bumped matplotlib and numpy versions

requirements.txt, setup.py
* pymongo 3.6.1 (pinning 3.6 was installing 3.6.0)
* psutil 5.4.2 (pinning 5.4 was installing 5.4.0)
=> Tidying up requirements for 1.5.0 release

mtools/mlaunch/mlaunch.py
=> mlaunch: failing to connect to a standalone SSL mongod

mtools/mlaunch/mlaunch.py
Retains pymongo import error exception, as suggested by @p
=> Retain pymongo import error exception. Fixes #660

mtools/mlaunch/mlaunch.py
handle case where the mongos logpath contains spaces
=> quote mongos --logpath argument

mtools/mlaunch/mlaunch.py
Unsupported config args like `--storageEngine` were removed from the options listed by `mongod --help`, but triggered a warning about being ignored if present on the command line. These options should only be passed to shard `mongod` instances.
=> Fix #730: --storageEngine confusingly reported as ignored in sharded deployments

mtools/mlaunch/mlaunch.py
Reverts rueckstiess/mtools#790
I don't think this change did anything useful.
=> Revert "Wait for each RS to elect a primary"

mtools/mlaunch/mlaunch.py
=> Cache the server's help and version output

mtools/mlaunch/mlaunch.py
- move current_version detection into init()
- support tls* params for MongoDB 4.2+, ssl* params for earlier versions
- use new tls* param names for PyMongo 3.9+
- fix flake8 complaints
=> Fix #784: mlaunch: add TLS aliases for SSL options

setup.py
Issue #834
Have initialised `install_requires` list.
It can be tested by following the installation steps of the package using Source code method.
O/S testing:
| Linux            | Ubuntu 20.04
| macOS            | 
| Windows          |
=> Initialised install_requires list

mtools/mloginfo/sections/clients_section.py, mtools/test/logfiles/client/mongod_3.0.5_noclientmetadata.log, mtools/test/logfiles/client/mongod_3.6.23.log, mtools/test/logfiles/client/mongod_4.2.11.log, mtools/test/logfiles/client/mongod_4.2.18_x509.log
This PR is for https://github.com/rueckstiess/mtools/issues/850.
Note that the effectiveness of this PR is impacted by an unrelated bug at https://github.com/rueckstiess/mtools/issues/871.
=> Issue 850: mloginfo: Improve --clients such that it includes more info for each Driver x Version x Application that has connected.
